server:
  port: 8080
  servlet:
    contextPath: /api

spring:
  application:
    name: sibs-demo
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    generate-ddl: false
    show-sql: false

    hibernate:
      ddl-auto: create-drop
      dialect: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
        default_schema: public

    javax:
      persistence:
        schema-generation:
          database:
            action: create
        create-database-schemas: true


logging:
  level:
    io:
      swagger:
        models:
          parameters:
            AbstractSerializableParameter: ERROR

#    '[org.springframework.data]': TRACE
#    '[org.hibernate]': TRACE
#    '[javax.persistence]': TRACE